version: '3.9'

services:
  db:
    image: postgres:15
    container_name: skuf_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skufdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    container_name: skuf_bot
    depends_on:
      - db
    environment:
      TELEGRAM_TOKEN: your_telegram_bot_token_here
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: skufdb
    restart: unless-stopped

volumes:
  pgdata:
